### ISSUE TITLE
Lists behavior in special cases is very strange, suggest removing

### ISSUE THREAD

**Issue by gavinpatkinson** [urbit/base-css#30]
When formatting legal text, it is useful to have classes like: 

```css
.legal ol {
  counter-reset: item;
}

.legal ol li {
  display: block;
}

.legal ol ol li {
  padding-left: 8rem;
}

.legal ol li:before {
  content: counters(item, ".") ".";
  counter-increment: item;
  display: inline-block;
  transform: translate(-10rem,5.825rem);
}

.legal .ls-alpha {
  counter-reset: item;
}

.legal .ls-alpha li:before {
  content: counter(item, lower-alpha) ".";
  counter-increment: item;
  display: inline-block;
  transform: translate(-10rem,5.825rem);
}
```

Base.css list classes have to be removed for this to work as expected. Its also my understanding that we generally don't use list styles from base. For these reasons I suggest removing any overrides for `<ol>`, `<ul>`, and `<li>` tags until we can specify more flexible and functional behavior.
